README.md

Tell developers that the Notion API is still in beta phase.

Add beta note to README

---

notion/client.go
notion/users_test.go
notion/version.go

Add "Notion-Version" header

---

.github/workflows/test.yml
notion/client.go
notion/search.go
notion/search_test.go
notion/users.go

For https://github.com/ketion-so/go-notion/issues/1
As title.

Support search API

---

README.md

Add badge for go pkg

---

notion/client.go
notion/database_test.go
notion/databases.go
notion/rich_text.go
notion/search.go
notion/users.go
notion/users_test.go

For #1 .
Note that it does not support querying the database. I will implement it later.

Add database API

---

.github/workflows/test.yml
README.md

Add test coverage

---

.github/workflows/test.yml

I've changed the default branch to main.

Change Ci target to main branch

---

notion/blocks.go
notion/blocks_test.go
notion/client.go

Add Block api

---

README.md

Add note for supported APIs

---

notion/blocks.go
notion/object/type.go
notion/users.go
notion/users_test.go

Provide types for Block and Users

---

README.md

Enable renovate

---

go.mod
go.sum
notion/blocks.go
notion/blocks_test.go
notion/object/type.go

Now, developers can cast to block type easily.

Add more flexible block type

---

.github/workflows/reviewdog.yml
.github/workflows/test.yml

As title. Add reviewdog and format check.

Improve CI

---

notion/blocks.go

Fix block list testis

---

notion/object/pages.go
notion/pages.go
notion/pages_test.go
notion/rich_text.go
notion/search.go

Part of https://github.com/ketion-so/go-notion/issues/16. 
Supports all parent property.

Add Page parent support

---

notion/blocks.go
notion/blocks_test.go
notion/databases.go
notion/object/property.go
notion/object/type.go
notion/pages.go
notion/rich_text.go
notion/search.go
notion/users.go

Add database property

---

notion/blocks.go
notion/client.go
notion/databases.go
notion/object/error.go
notion/pages.go
notion/search.go
notion/users.go

Add correct error type.
For https://github.com/ketion-so/go-notion/issues/16

Add error type

---

.mergify.yml
README.md

Add reviewdog badge

---

notion/search.go
notion/search_test.go

Add search object

---

notion/blocks.go
notion/client.go
notion/databases.go
notion/pages.go
notion/search.go
notion/users.go

Improve test coverage

---

notion/blocks.go
notion/client.go
notion/databases.go
notion/pages.go
notion/search.go
notion/users.go

Refactor common check. Part of https://github.com/ketion-so/go-notion/issues/33

Refactor test client check

---

notion/client_test.go

Add client do tests

---

notion/object/error.go

Fix error const name

---

notion/blocks.go
notion/pages.go

Fix API method of patch APIs

---

notion/blocks.go
notion/databases.go
notion/object/error.go
notion/object/pages.go
notion/object/property.go
notion/object/type.go
notion/pages.go

As title. Fixed some warnings.

Fix for golint

---

notion/blocks.go
notion/client.go
notion/databases.go
notion/pages.go
notion/rich_text.go
notion/search.go
notion/users.go

Add comments regarding the goreport results.

Add comments

---

notion/search.go

Fix typo in comment

---

notion/client.go
notion/client_test.go
notion/object/type.go

Add error resp test

---

notion/client_test.go

Add tests for client

---

notion/pages.go
notion/pages_test.go

As title. No need to pass the Page ID. Typo.

Fix page creation API

---

notion/pages.go
notion/pages_test.go

Don't use pointer for interfaces 😢

Fix parent field in page

---

notion/database_test.go
notion/databases.go
notion/pages_test.go
notion/property.go
notion/rich_text.go
notion/search_test.go

Change property to object

---

notion/database_test.go
notion/pages_test.go
notion/rich_text.go
notion/search_test.go

Fix text object

---

notion/pages_test.go
notion/property.go

Add some objects

---

notion/pages.go
notion/pages_test.go

As title. Needs to fix this bug.

Update property args

---

notion/database_test.go
notion/databases.go
notion/search.go

Add Database query

---

notion/property.go
notion/users.go

Fine field types for properties

---

notion/property.go

Fix people property

---

notion/databases.go

Bug fixture 🐛 If will fail because it has wrong field.

Fix sort to sorts for db query

---

notion/search.go

Add `omitempty` for property..

Fix omitempty for sort property

---

notion/pages.go

Add `omitempty` to parent types.

Add "omitempty" to parent type
